apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/kubernetes-cloud/locations/us-central1-c/clusters/autopilot-cluster-1

